Bug fix cnm variant compilation
EyeSeeTea/pictureapp pull request #1513
Opened 2017-09-20 10:34 UTC by manuelplazaspalacio

Close #1506

2017-09-28 06:30 UTC, xurxodev requested changes
@manuelplazaspalacio the behavior has changed with current credentials null management. For example When user is not in demo mode and is not logged (null credentials), in these case surveys should not appears never in send list after push process, 
Can you review whole null credentials management?

2017-09-28 06:30 UTC, xurxodev commented on app/src/cnm/java/org/eyeseetea/malariacare/domain/usecase/LoginUseCase.java
> +                        if (credentials == null && !credentials.isDemoCredentials()) {
if credentials is null on execute we should throw IllegalArgumentException, so validate null onSuccess is not necesary

2017-09-28 06:30 UTC, xurxodev commented on app/src/cnm/java/org/eyeseetea/malariacare/services/strategies/PushServiceStrategy.java
> +        if (Session.getCredentials() == null || Session.getCredentials().isDemoCredentials()) {
if credentials is null should not execute mocked push

2017-09-28 06:30 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/ProgressActivity.java
> +        launchPull(
null credentials and demo credentials is no the same case

2017-09-28 06:30 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/data/authentication/AuthenticationManager.java
> +        if (credentials == null || credentials.isDemoCredentials()) {
if credentials is null on login we should throw IllegalArgumentException because null credentials and demo credentials is not the same case

2017-09-28 06:30 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/network/ServerAPIController.java
> +        if (Session.getCredentials() == null || Session.getCredentials().isDemoCredentials()) {
null credentials and demo credentials is not the same case

2017-09-28 13:34 UTC, manuelplazaspalacio commented
Changes done @xurxodev

2017-09-29 06:29 UTC, xurxodev approved these changes
thanks @manuelplazaspalacio

2017-09-29 06:29 UTC, merged