Bug push stop working losing connection
EyeSeeTea/pictureapp pull request #1525
Opened 2017-09-27 11:23 UTC by manuelplazaspalacio

Close #1518

2017-09-28 04:48 UTC, xurxodev requested changes
@manuelplazaspalacio I have requested you some changes, can you review it please?

2017-09-28 04:48 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/domain/usecase/LoginUseCase.java
> +        if (orgUnitCredentials != null) {
if orgUnitCredentials can be null if network fail to retrieve credentials from the server then in the checkUserCredentialsWithOrgUnit method we should validate null

2017-09-28 10:32 UTC, manuelplazaspalacio commented
Changes done @xurxodev

2017-09-29 04:36 UTC, xurxodev approved these changes
thanks @manuelplazaspalacio

2017-09-29 04:36 UTC, merged