Feature auto configuration
EyeSeeTea/pictureapp pull request #1529
Opened 2017-09-29 16:18 UTC by manuelplazaspalacio

Close #1504

2017-10-02 06:25 UTC, xurxodev requested changes
@manuelplazaspalacio I have requested you some changes. please, can you review it?

2017-10-02 06:25 UTC, xurxodev commented on app/src/cnm/java/org/eyeseetea/malariacare/strategies/SplashActivityStrategy.java
> +                        continueWithDemoUser();
when autoconfiguration fail, the app should not continue with demo user, you must do nothing, you will be in no-login mode

2017-10-02 10:05 UTC, manuelplazaspalacio commented
Changes done @xurxodev

2017-10-03 05:13 UTC, xurxodev requested changes
@manuelplazaspalacio I have found some problems:
- when on pull process occurred either error the autoconfiguration message is shown but this message should be shown only for autoconfiguration error. I think we should create an AutoconfigurationException in domain for CNM and for avoid realize many changes we can change message parameter in onError usecase callback to Throwable then in other variants get the message and execute the same code and on CNM if Throwable is AutoconfigurationException show the correct dialog.
- if autoconfiguration is completed in push process when ban orgunit is realized an exception occurred and push fail
- When autoconfiguration fail, this is the final step the pull process, then has no sense execute pull again. 
- When autoconfiguration is complete, if I click on autoconfiguration in settings we should call to server again for get orgunit

2017-10-03 16:58 UTC, manuelplazaspalacio commented
Solved bugs @xurxodev

2017-10-04 06:06 UTC, xurxodev approved these changes
thanks @manuelplazaspalacio

2017-10-04 06:06 UTC, merged