show a warning if exists more than one org unit by phone
EyeSeeTea/pictureapp pull request #1557
Opened 2017-10-24 04:40 UTC by xurxodev

close #1552

2017-10-24 15:00 UTC, ifoche requested changes
@xurxodev Just a cosmetic thing, but I prefer you to review it and tell me if I'm missing something rather than changing it myself

2017-10-24 15:00 UTC, ifoche commented on app/src/main/java/org/eyeseetea/malariacare/network/ServerAPIController.java
> +                moreThanOneOrgUnit = true;
@xurxodev do we need this flag? couldn't we just ask for orgUnitsArray.length()>1 down in the condition to throw the exception?

2017-10-25 04:32 UTC, xurxodev commented
@ifoche I have removed unnecessary flag

2017-10-25 06:26 UTC, ifoche approved these changes
thanks @xurxodev

2017-10-25 06:26 UTC, merged