Putting eVoucher in list for phone vouchers
EyeSeeTea/pictureapp pull request #1563
Opened 2017-10-25 09:10 UTC by manuelplazaspalacio

Close #1559

2017-10-25 09:22 UTC, ifoche requested changes
@manuelplazaspalacio just a minor change in how you retrieve the value from the DB and loop on the values

2017-10-25 09:22 UTC, ifoche commented on app/src/ereferrals/java/org/eyeseetea/malariacare/layout/adapters/dashboard/strategies/DashboardAdapterStrategy.java
> +    private boolean hasPhone(SurveyDB survey) {
@manuelplazaspalacio maybe we could improve the performance of this by using a join? Is there any reason for not doing it?

2017-10-25 12:01 UTC, manuelplazaspalacio commented
Refactor has phone method @ifoche

2017-10-26 18:26 UTC, ifoche approved these changes
thanks @manuelplazaspalacio

2017-10-26 18:26 UTC, merged