show questions label in review screen
EyeSeeTea/pictureapp pull request #1662
Opened 2017-11-13 12:25 UTC by xurxodev

close #1645

2017-11-13 12:27 UTC, xurxodev commented
@ifoche I have created an issue https://github.com/EyeSeeTea/pictureapp/issues/1660 to review this feature in all variants because there is duplicated code

2017-11-14 10:15 UTC, ifoche requested changes
@xurxodev only a minor change requested

2017-11-14 10:15 UTC, ifoche commented on app/src/cnm/java/org/eyeseetea/malariacare/strategies/ReviewScreenAdapterStrategy.java
> +        TextView answerText = (TextView) rowView.findViewById(R.id.review_answer);
@xurxodev here it would be better to use a CustomTextView, right?

2017-11-14 14:56 UTC, xurxodev commented
@ifoche It's done

2017-11-14 15:59 UTC, ifoche approved these changes
thanks @xurxodev

2017-11-14 15:59 UTC, merged