Feature new balance receipt screen
EyeSeeTea/pictureapp pull request #1706
Opened 2017-12-12 13:27 UTC by manuelplazaspalacio

Close #1688

2018-03-06 09:26 UTC, xurxodev requested changes
@manuelplazaspalacio After to merge with development and resolve many changes, this branch is not showing new fragment to create new stock surveys when tap on the new stock survey buttons, can you review what is the problem? thanks

2018-03-07 07:14 UTC, xurxodev requested changes
@manuelplazaspalacio I have requested you some changes. Can you review it, please?

2018-03-07 07:14 UTC, xurxodev commented on app/src/cnm/java/org/eyeseetea/malariacare/fragments/StockSurveysFragment.java
> +                mStockSurveysPresenter.onAddBalanceClick(getActivity());
Here you are setting activity argument to a presenter but the presenter is only presentation logic and a presenter should not know anything about Android Framework

2018-03-07 07:14 UTC, xurxodev commented on app/src/cnm/java/org/eyeseetea/malariacare/fragments/StockSurveysFragment.java
> +                mStockSurveysPresenter.onAddReceiptClick(getActivity());
Here you are setting activity argument to a presenter but the presenter is only presentation logic and a presenter should not know anything about Android Framework

2018-03-07 07:14 UTC, xurxodev commented on app/src/cnm/java/org/eyeseetea/malariacare/layout/adapters/survey/AddBalanceReceiptAdapter.java
> +public class AddBalanceReceiptAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
If the save button is an element of item list this adapter is more complicated, I think is more natural extract save button from recycler view. Can you refactor it?

2018-03-07 07:14 UTC, xurxodev commented on app/src/cnm/java/org/eyeseetea/malariacare/presentation/presenters/StockSurveysPresenter.java
> +    private void showNewReceiptBalanceFragment(int type, Activity activity) {
This method should not be in presenter because a presenter should not know anything about activities or fragments. Better if you add a new method showNewReceiptSurvey in StockView and StockSurveysFragment implements this method.

2018-03-07 07:14 UTC, xurxodev commented on app/src/cnm/java/org/eyeseetea/malariacare/presentation/presenters/StockSurveysPresenter.java
>  import android.app.Activity;
A presenter should not have any dependency of Android framework. This presenter still contains a broadcast receiver. I have reviewed the following issues and unless I have escaped something this is not refactored in next issues. Can you do it on this issue or tell me which issue is changed?

2018-03-07 07:14 UTC, xurxodev commented on app/src/cnm/java/org/eyeseetea/malariacare/presentation/presenters/AddBalanceReceiptPresenter.java
> +import android.util.Log;
A presenter should not have any dependency of Android framework.

2018-03-07 07:14 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/data/database/datasources/SurveyLocalDataSource.java
> +    public Survey save(Survey survey) {
this change is not necessary, a save method should return void, the survey is not a primitive type and is passes as a reference.

2018-03-07 07:14 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/boundary/repositories/IQuestionRepository.java
> +    List<Question> getQuestionsForProgram(String programUID);
please rename this better to getQuestionsByProgram

2018-03-07 07:14 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/usecase/GetQuestionsForProgramUseCase.java
> +public class GetQuestionsForProgramUseCase implements UseCase {
Please rename this class better to GetQuestionsByProgramUseCase

2018-03-07 07:14 UTC, xurxodev commented on app/src/cnm/java/org/eyeseetea/malariacare/layout/adapters/survey/AddBalanceReceiptAdapter.java
> +        mOnInteractionListener.onQuestionAnswered(question,
the logic to initialize to zero the questions should be in presenter but here is realized in adapter, can you refactor it?

2018-03-07 10:43 UTC, manuelplazaspalacio commented on app/src/cnm/java/org/eyeseetea/malariacare/layout/adapters/survey/AddBalanceReceiptAdapter.java
> +public class AddBalanceReceiptAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
This is done in issue #1819

2018-03-09 06:06 UTC, xurxodev approved these changes
thanks @manuelplazaspalacio

2018-03-09 06:06 UTC, merged