Disabling user can edit survey when push returns response code 403.
EyeSeeTea/pictureapp pull request #1725
Opened 2018-01-07 11:27 UTC by manuelplazaspalacio

Close #1720

2018-01-18 15:08 UTC, manuelplazaspalacio commented
Close #1720

2018-01-25 06:05 UTC, ifoche requested changes
@manuelplazaspalacio there's a failing tests, can you check it please? Thanks!

2018-01-25 06:05 UTC, ifoche commented on app/src/androidTestEreferrals/java/org/eyeseetea/malariacare/SettingsActivityShould.java
> +public class SettingsActivityShould {
This test is failing for me. Can you take a look @manuelplazaspalacio ?

2018-01-25 07:08 UTC, ifoche approved these changes
thanks @manuelplazaspalacio, I've created the separate issue #1767 to deal with the SettingsActivityShould problem but accepting this code

2018-01-25 07:08 UTC, merged