Feature cnm survey design
EyeSeeTea/pictureapp pull request #1868
Opened 2018-03-09 12:49 UTC by manuelplazaspalacio

Close #1867

2018-03-09 16:16 UTC, manuelplazaspalacio commented
This issue needs issue #1862 to be merged before.

2018-03-13 06:43 UTC, ifoche requested changes
@manuelplazaspalacio a few comments that come probably as the result of the merge with so many modifications in csvs. I'm sure you can solve this much more quickly than me. 

- In Diagnosis method question, options should be centered
![screenshot_20180313-073049](https://user-images.githubusercontent.com/10931645/37326297-bb9bc60e-2691-11e8-8888-759a8ede25cf.png)

- In test result, could the images be a bit bigger? I guess it's a matter of just adjusting a bit more the image to the edges of the file
![screenshot_20180313-073116](https://user-images.githubusercontent.com/10931645/37326358-1bd4bc38-2692-11e8-9a44-5e15dfc301af.png)

- When 'Not tested' option is clicked, it takes you to stock question
![screenshot_20180313-073149](https://user-images.githubusercontent.com/10931645/37326385-3a4c2ea8-2692-11e8-8c34-78942db028bd.png)

Thanks!

2018-03-13 09:05 UTC, ifoche requested changes

2018-03-13 09:05 UTC, ifoche commented on app/src/cnm/assets/Questions.csv
> +19;'Code: Referred';'ipc_issueEntry_q_referred';;'ipc_issueEntry_q_referred';'Weypkpeu9Z8';3;0;0;1;20;;32;8;0;;1
@manuelplazaspalacio there's a conflict with this 2 DEs that has Weypkpeu9Z8 UID. Actually there's no DE in the server with that UID. Can you have a look? Thanks!

2018-03-13 10:14 UTC, ifoche approved these changes
thanks @manuelplazaspalacio

2018-03-13 10:14 UTC, merged