Feature ereferals intent from other app
EyeSeeTea/pictureapp pull request #2094
Opened 2018-05-09 23:12 UTC by idelcano

Closes #2034

2018-05-10 11:36 UTC, xurxodev requested changes
@idelcano I have found some problems to review:
## Features
### No user logged in. Show a toast with the error and close connect 
Not work
### In case auth parameters are not provided in the intent (they are optional), the login must allow the user to enter them (only for soft-login)
- if auth does not exists -> work but If username and password is equal to null then connect crash and if username and password is equal to empty then not work. For me, all these situations should work like when auth does not exist
## Changes in code
I have found some code to refactor in a first review, I have inserted comments in PR code

2018-05-10 11:36 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/DashboardActivityStrategy.java
> +    private void parseJsonValuesAndSave(SurveyDB survey, String jsonValues) throws IOException {
this method has more a one responsibility, can you, for example, create a mapper class that encapsulates mapping logic?

2018-05-10 11:36 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/DashboardActivityStrategy.java
> +    private void saveValue(SurveyDB survey, String key, String value) {
this method seems duplicate with others on the app, can you refactor to avoid duplicate code?

2018-05-10 11:36 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
> +        if(loginActivity.getIntent().getStringExtra(SplashScreenActivity.INTENT_JSON_EXTRA_KEY)==null
can you extract this condition to a function for has a more readable code?

2018-05-10 11:36 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
> +                if (credentials != null && !credentials.isEmpty()) {
please, can you refactor this anonymous method for avoiding nested ifs (for example creating functions) for has a more readable code?

2018-05-10 11:36 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
> +        Thread thread = new Thread(){
for this purpose better use a handler and postDelayed function

2018-05-10 11:36 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
> +    private ConnectVoucher parseJson(String jsonToSend) {
duplicate code for deserialize ConnectVoucher, can you refactor it?

2018-05-14 15:23 UTC, xurxodev requested changes
@idelcano  I think the code can to be refactored a little more for we have a more readable code: I have inserted comments in the code

2018-05-14 15:23 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/DashboardActivityStrategy.java
> +        SurveyDB surveyDB = new SurveyDB(null, programDB, Session.getUserDB());
On this method SurveyDB and Survey domain entities are used, can you refactor for only use domain entity?

2018-05-14 15:23 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/DashboardActivityStrategy.java
> +                    ConnectVoucher connectVoucher = ConnectVoucherMapper.parseJson(valuesJson);
we should have a mapper and mapper should map and return all ConnectVoucher with values, here should not insert loops for convert values

2018-05-14 15:23 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/DashboardActivityStrategy.java
> +        surveyDB.save();
Can you refactor this for use SaveSurveyUseCase to save?

2018-05-14 18:44 UTC, idelcano commented
@xurxodev  i moved the Session.setMalariaSurveyDB to the SurveyLocalSource
https://github.com/EyeSeeTea/pictureapp/commit/738be7b6e71076249b702574bb5844befcbef7d6

2018-05-16 11:16 UTC, xurxodev requested changes
@idelcano the code is a bit dirty still, I have trouble understanding it yet, I've put some more improvements

2018-05-16 11:16 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
> +                ConnectVoucher connectVoucher = ConnectVoucherMapper.parseJson(valueFromOtherApp);
This verification can be realized previously to execute getLastInsertedCredentialsUseCase, can you refactor it?

2018-05-16 11:16 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/LoginActivityStrategy.java
> +        return connectVoucher.getAuth().getUserName().equals(credentials.getUsername())
this code can be refactored to more simple comparing only Auth objects and overriding equals and hashcode in auth object

2018-05-16 11:16 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/views/question/multiquestion/PhoneMultiQuestionView.java
> +        IPhoneFormatRepository phoneLocalDataSource = new PhoneFormatLocalDataSource();
The responsibility of a custom view should only be a view but here also search the phone format. I think is more correct configure this view with a format from outside. We would add a Configureformat method and invoke it.

2018-05-16 11:16 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/strategies/ADashboardActivityStrategy.java
> +        if(!DashboardActivity.dashboardActivity.isPreLoadSurveyOpenning()) {
Please intent don't use static methods for avoid memory leaks

2018-05-16 11:16 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/DashboardActivityStrategy.java
> +        UserAccount userAccount = new UserAccount(Session.getUserDB().getName(),
can you refactor this for GetUserUserAccountUseCase instead of use session for create UserAccount?

2018-05-16 11:16 UTC, xurxodev commented on app/src/ereferrals/java/org/eyeseetea/malariacare/strategies/DashboardActivityStrategy.java
> +        IMainExecutor mainExecutor = new UIThreadExecutor();
mainExecutor and AsyncExecutor are created three times in this class, can you optimize it?

2018-06-04 07:21 UTC, xurxodev approved these changes
thanks @idelcano. Congratulations now on this issue you have intent to realize the task with clean architecture. I have created an issue to review it because there are some parts of the code to improve but now we have not time. 
The are some bug creating many in progress surveys. Sometimes the app show old sent survey instead of last sent survey but this will be solved in issue #2120

2018-06-04 07:22 UTC, merged